services:
  vert:
    container_name: vert
    image: VERT-sh/vert:latest
    environment:
      - PUB_HOSTNAME=${PUB_HOSTNAME:-vert.sh}
      - PUB_PLAUSIBLE_URL=${PUB_PLAUSIBLE_URL:-https://plausible.example.com}
      - PUB_ENV=${PUB_ENV:-production}
      - PORT=${PORT:-3000}
      - PUB_VERTD_URL=${PUB_VERTD_URL:-https://vertd.vert.sh}
    build:
      context: .
      args:
        PUB_HOSTNAME: ${PUB_HOSTNAME:-vert.sh}
        PUB_PLAUSIBLE_URL: ${PUB_PLAUSIBLE_URL:-https://plausible.example.com}
        PUB_ENV: ${PUB_ENV:-production}
        PUB_VERTD_URL: ${PUB_VERTD_URL:-https://vertd.vert.sh}
    restart: unless-stopped
    ports:
      - ${PORT:-3000}:80
